### ISSUE TITLE
[HW3] task no.3 (branch coverage of kcov-branch-identify)

### ISSUE THREAD

**Issue by kws1207** [swtv-kaist/cs458-spring23#16]
When I run `gcov -b kcov-branch-identify`, it also generates output and .gcov file of every header files.

1. Am I doing it right?
2. If so, should I report coverage of all those headers or only coverage of `kcov-branch-identify.cpp`?

Thank you.

**Comment by kws1207** [comment]
Additional question: 
3. In task no.3, should `test_script` contain scripts that execute `make` and/or `gcov`?

**Comment by swtv-kaist** [comment]
A1. A2. You can report .gcov file for kcov-report-identify.cpp only, since we would like to focus to test the code we write (i.e., we trust header files like standard libraries, since header files contain code written by expert developers).  

A3. ```test_script``` should contain ```gcov``` to show the coverage at runtime, but may not contain ```make``` which is an activity at static time.

**Comment by kws1207** [comment]
Thank you
