### ISSUE TITLE
Counter example which states PPC doesn't subsume EPC

### ISSUE THREAD

**Issue by duncan020313** [swtv-kaist/cs458-spring23#26]
If there is node N1 which have self loop,

The path [N0, N1, N1] is TR for EPC. But it is not a simple path because there is internal loop [N1, N1].
Thus PPC doesn't subsume EPC in this case.

Did we ever talked let's ignore it?
Sorry for late question...

**Comment by swtv-kaist** [comment]
The subsumption relation between coverage criteria is not about their TR, but test inputs that satisfy the TR.

```Criteria Subsumption: A coverage criterion C1 subsumes C2 if and only if every test set that satisfies criterion C1 also satisfies C2.```

[N0, N1, N1] is not in TR of PPC, but [N1, N1] is.  Thus, any test input that covers [N1, N1] will cover [N0, N1, N1] since N0 is an initial node.

**Comment by jaehyun1ee** [comment]
Then, what about [N1, N1, N1]? It is covered by EPC, but can it be covered by PPC?

**Comment by swtv-kaist** [comment]
> Then, what about [N1, N1, N1]? It is covered by EPC, but can it be covered by PPC?
![image](https://user-images.githubusercontent.com/29851315/232662365-2ed06e1d-0129-4a20-8585-15544d7ca863.png)

1.
Since the target graph does not have a branch, all test inputs will execute the same path.  Thus, [N1,N1,N1] will be covered by a test input satisfying PPC.

2.
Exactly speaking, since the target graph does not have a final node, there is no available test path.

**Comment by jaehyun1ee** [comment]
![image](https://user-images.githubusercontent.com/44872014/232663302-440c5b09-a047-488d-8d5c-8eb6538af289.png)

Oh, I see. Then this may be a more appropriate example that I have intended. 

The prime paths here are [N1, N1] and [N0, N1, N2]. So a test set T = {[N0, N1, N2], [N0, N1, N1, N2]} would satisfy PPC. But this fails to satisfy EPC because it fails to tour [N1, N1, N1]. Is my observation right?

Sorry for lagging on this question. It is quite tough to understand the subsumptions because there are some corner cases.

**Comment by Allgot** [comment]
It seems rational when considering graphs purely. In graphs, the constraints are just 'N is not empty, N0 is not empty and Nf is not empty' according to slides.

However, since we do not allow such self-loop when translating the code into a graph(refer to p6 of 'lec5-graph-coverage-code'), we can safely assume that there is not such self-loop.

With this assumption, we can prove that PPC subsumes EPC using the fact that any internal loop's length is at least 3.

**Comment by duncan020313** [comment]
I think the problem is resolved. Thank you for your answers.
