### ISSUE TITLE
[HW06] Can queue of afl-fuzz contain non-terminating test inputs?

### ISSUE THREAD

**Issue by jaehyun1ee** [swtv-kaist/cs458-spring23#33]
Hi, I have some questions regarding the odd behavior of `afl-fuzz`.

**1. Can the `queue` directory contain non-terminating tests?**

After fuzzing with my custom driver, I have some fuzzed test case in `queue` directory, that doesn't terminate when I actually run them manually.

For example, there is one test in `queue` that is equivalent to executing `./grep -f- tmp`. 
(i.e., the driver eventually runs that command, where `./grep` here is the non-instrumented, original `grep` binary)

The odd part is that, `./grep -f- tmp` falls into an infinite loop, while parsing the command line options in a while loop in `grep.c::main`.

So I wonder how this testcase is in `queue`, not in `hang`. Does `queue` also hold non-terminating inputs?

**2. Is the implementation choice of the grep driver up to us?**

I tried implementing the custom driver following the suggestion in the class, regarding the first line as command-line options and the rest as the target of `grep`.

However, there are some problems, including the one mentioned above.

Instead of such a general approach, I want to implement a driver that is aware of grep command-line options, to make sure that the command-line options are at least, valid.

Is the implementation choice up to me as long as afl++ reports a coverage over 60%?

**Comment by YoungseokCh** [comment]
>  1. Can the queue directory contain non-terminating tests?

Thank you for the question. The queue directory should have only non-terminating test cases. In the case of command `./grep -f- tmp`, it is waiting for the standard input. You can check `echo x | grep -f- tmp` terminates immediately by feeding the standard input 'x'.

It's because `afl-fuzz` feeds empty standard inputs when it runs the fuzzing campaign. As a hint, you can feed empty input by

```shell
grep -f- tmp < /dev/null
```

when you replay the testcases in the `queue` directory.

> 2. Is the implementation choice of the grep driver up to us?

The general approach is encouraged because `grep` is expected to handle all kinds of command line inputs and it is easy to implement it. If you are really in trouble, you can do it that way, but not suggested.

**Comment by jaehyun1ee** [comment]
Thank you for your kind help, as always :)
